---
# tasks file for show_router_facts

- name: gather facts from IOS device
  ios_facts: 
    gather_subset: "!config"
  register: ios_info
  

- name: display device ID
  debug:
   msg:
   - "Hostname: {{ ansible_net_hostname }}"
   - "Model: {{ ansible_net_model }}"
   - "Serial Num: {{ ansible_net_serialnum  }}"

- name: display device info
  debug:
    msg: "{{ ios_info }}"
