---
# tasks file for show_router_facts

- name: gather facts from IOS device
  ios_facts: 
    gather_subset: "!config"
  register: ios_info
  

- name: display hostname
  debug:
   msg:
   - "Hostname: {{ ansible_net_hostname }}"
   - "Model: {{ ansible_net_model }}"

- name: display model
  debug:
   msg: "Model: {{ ansible_net_model }}"

- name: display serial number
  debug:
   msg: "Model: {{ ansible_net_serialnum  }}"

- name: template display
  debug:
   msg: "{{ lookup('template', 'template.j2') | to_json }}"

- name: output
  debug:
    msg: "{{ ios_info }}"
